services:
  georwell-api:
    image: thrsouza/georwell
    container_name: georwell-api
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://georwell-database:27017/georwell
      - PORT=3000
    depends_on:
      - georwell-database

  georwell-database:
    image: mongo
    container_name: georwell-database
    ports:
      - "27017:27017"
