services:
  books_api:
    image: thrsouza/books-api
    container_name: books_api
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://books_db:27017/books-db
      - PORT=3000
    depends_on:
      - books_db

  books_db:
    image: mongo
    container_name: books_db
    ports:
      - "27017:27017"
